services:
  my-monorepo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3000}
        - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/postgres}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-your-secret-key}
    container_name: my-monorepo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3000}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/postgres}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-your-secret-key}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
