[phases.setup]
nixPkgs = ["nodejs_22", "bun", "pnpm"]
nixpkgsArchive = "master"

[phases.install]
dependsOn = ["setup"]
commands = ["pnpm install"]

[phases.build]
commands = ["bun run build"]

[start]
cmd = "bun run start"
