[phases.setup]
nixPkgs = ['nodejs_22', 'bun']
nixpkgsArchive = 'f69ae4816bc1b501460ad2c0c63ed0cc4a9b876e'

[phases.install]
dependsOn = ['setup']
commands = ["bun install"]

[phases.build]
commands = ["bun run build:production"]

[start]
cmd = "bun run start:production"
